### ISSUE TITLE
Not wokring in python 2.7.5

### ISSUE THREAD

**Issue by sebo83910** [MircoT/pyTGA#3]
Hello,

just tried the example.py in python 2.7 (you said it was compatible with python2...). 
I ran into this error:

[sebo@ws pyTGA-master]$ python example.py
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    main()
  File "example.py", line 28, in main
    image.save("image_black_and_white")
  File "/home/sebo/AXI_SCALER/temp/pyTGA-master/pyTGA/tga.py", line 644, in save
    image_file.write(self._header.to_bytes())
  File "/home/sebo/AXI_SCALER/temp/pyTGA-master/pyTGA/tga.py", line 218, in to_bytes
    tmp += gen_byte(self.id_length)
  File "/home/sebo/AXI_SCALER/temp/pyTGA-master/pyTGA/tga.py", line 60, in gen_byte
    return pack(order + format_, data)
TypeError: Struct() argument 1 must be string, not unicode
[sebo@ws pyTGA-master]$ python3 example.py
175
[[0, 255, 0, 175], [0, 0, 255, 0], [255, 255, 255, 0]]

python 3 is working.

**Comment by MircoT** [comment]
Hi,

I changed the code to force the substitution and concat in string mode, both for python 2 and 3. By the way, I don't have such an error with python 2 but, I need to know your OS version too. I'm curretly testing from macOS.

Let me know if you still have that problem after the update. Thanks for the opening issue.
