### ISSUE TITLE
struct.error: ubyte format requires 0 <= number <= 255

### ISSUE THREAD

**Issue by Bra1nsen** [MircoT/pyTGA#6]
```
import pyTGA

data_rgb = [
[(0, 0, 0), (255, 0, 0), (0, 0, 0), (0, 0, 0)],
[(0, 0, 0), (0, 0, 0), (255, 0, 0), (0, 0, 0)],
[(255, 0, 0), (255, 0, 0), (315, 0, 0), (0, 0, 0)]
]

# Create from grayscale data
image = pyTGA.Image(data=data_rgb)
# Save as TGA
image.save("image_bckte")
```

**Traceback (most recent call last):
  File "/home/pi/testrawbayer/pyTGA/tests/acc.py", line 10, in <module>
    image = pyTGA.Image(data=data_rgb)
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 413, in __init__
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 350, in __init__
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 361, in __buffer_from_data
struct.error: ubyte format requires 0 <= number <= 255**

16Bit use values beyond 255 I thought :(

**Comment by MircoT** [comment]
> 16Bit use values beyond 255 I thought :(

Yep. RGB values could be 8bit per color.
